# Generated by Django 3.2.13 on 2022-06-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Origin_Url', models.TextField()),
                ('Short_Url', models.TextField()),
                ('visit_Count', models.IntegerField()),
            ],
        ),
    ]
