# Generated by Django 3.2.13 on 2022-06-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='Short_Path',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='url',
            name='visit_Count',
            field=models.IntegerField(default=0),
        ),
    ]
